// KPI's:
Total Loan Application = DISTINCTCOUNT(financial_loan[ID])
Total Loan Amount = SUM(financial_loan[LOAN_AMOUNT])
Total Amount Received = SUM(financial_loan[TOTAL_PAYMENT])
Avg. INT Rate = AVERAGE(financial_loan[INT_RATE])
Ag. DTI Rate = AVERAGE(financial_loan[DTI])

// Good Loan Calculations:

Total Loan Applications (GD) = CALCULATE(COUNTROWS(financial_loan), financial_loan[LOAN_STATUS] IN {"Fully Paid", "Current"})
Total Founded Amount (GD) = CALCULATE(SUM(financial_loan[LOAN_AMOUNT]), financial_loan[LOAN_STATUS] IN {"Fully Paid", "Current"})
Total Amount Recived (GD) = CALCULATE(SUM(financial_loan[TOTAL_PAYMENT]), financial_loan[LOAN_STATUS] IN {"Fully Paid", "Current"})

% Good Loan = 
        VAR _GoodLoan = [Total Loan Applications (GD)]
        VAR _TotalAppliation = [Total Loan Application]
        RETURN
          DIVIDE(_GoodLoan, _TotalAppliation)

//Bad Loan Calculations:
Total Loan Applications (BD) = CALCULATE(COUNTROWS(financial_loan), financial_loan[LOAN_STATUS] IN {"Charged Off"})
Total Founded Amount (BD) = CALCULATE(SUM(financial_loan[LOAN_AMOUNT]), financial_loan[LOAN_STATUS] IN {"Charged Off"})
Total Amount Recived (BD) = CALCULATE(SUM(financial_loan[TOTAL_PAYMENT]), financial_loan[LOAN_STATUS] IN {"Charged Off"})

% Bad Loan Application = 
            VAR _BadLoan = [Total Loan Applications (BD)]
            VAR _TotalApplication = [Total Loan Application]
            RETURN
              DIVIDE(_BadLoan, _TotalApplication)

